### ISSUE TITLE
Unistall EasyNewsLetter 2.6.x (now 2.6.15) fails with KeyError: u'profile-inqbus.plone.fastmemberproperties:uninstall'

### ISSUE THREAD

**Issue by oxygenius** [collective/Products.EasyNewsletter#86]
I need to uninstall EasyNewsLetter to upgrade to plone 5, without losing functionality from the new plone5 toolbar. I localized EasyNewsLetter to be the pain in the back.
I upgrade to latest plone 4 (4.3.11 - 4314). And I upgraded from EasyNewsLetter 2.6.14 to 2.6.15
But I still cannot deactivate EasyNewsLetter. I get the following error:

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module <string>, line 4, in uninstallProducts
Module AccessControl.requestmethod, line 70, in _curried
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 743, in uninstallProducts
Module Products.CMFQuickInstallerTool.InstalledProduct, line 286, in uninstall
Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
__traceback_info__: profile-Products.EasyNewsletter:uninstall
Module Products.GenericSetup.tool, line 1339, in _runImportStepsFromContext
Module Products.GenericSetup.tool, line 1283, in getProfileDependencyChain
Module Products.GenericSetup.tool, line 1281, in getProfileDependencyChain
Module Products.GenericSetup.tool, line 915, in getDependenciesForProfile
KeyError: u'profile-inqbus.plone.fastmemberproperties:uninstall'

What can I do to remove EasyNewsLetter to continue my plone upgrade path?

**Comment by oxygenius** [comment]
Hi Maik,

Thank you for your response. I would try your suggestion, but I found; wildcard.fixpersistentutilities

It helped me to get rid of all remaining dependencies.

Thanks again. I hope there will be a plone 5 version of EasyNewsLetter available later on.

Regards,

Lars Dam

Van: Maik Derstappen [mailto:notifications@github.com]
Verzonden: woensdag 28 september 2016 15.29
Aan: collective/Products.EasyNewsletter
CC: Lars Dam; Author
Onderwerp: Re: [collective/Products.EasyNewsletter] Unistall EasyNewsLetter 2.6.x (now 2.6.15) fails with KeyError: u'profile-inqbus.plone.fastmemberproperties:uninstall' (#86)


as a workaround you could just try to install inqbus.plone.fastmemberproperties, if that doesn't help, try to manipulate the profiles in the package directly in your filesystem and remove the dependency in the uninstall profile. Then restart your Plone and try again.

**Comment by MrTango** [comment]
On 29.09.2016 12:20, oxygenius wrote:
> Hi Maik,
>
> Thank you for your response. I would try your suggestion, but I found;
> wildcard.fixpersistentutilities
>
> It helped me to get rid of all remaining dependencies.
>
> Thanks again. I hope there will be a plone 5 version of EasyNewsLetter
> available later on.
>
Hi Lars,

yes the will be a version for Plone 5.
Actually the master is already running on Plone 5/4.
But we need to rewrite some tests, so that they will work for Plone 5 and 4.
And also we would like to change the async delivery from AMQP based to
collective.taskqueue based.
Then we will make a release which runs on both Plone 4 and 5.


-- 
viele Grüße
Maik Derstappen

--
Maik Derstappen
Geschäftsführer

derico - web development & consulting
-- Python - Plone - Zope - Pyramid - Django --
Demmeringstr. 57 - 04177 Leipzig - Deutschland
Tel: +49 178 861 2 833 - E-Mail: md@derico.de - Web: http://derico.de

-- help --
Ask your Plone questions on Gitter: https://gitter.im/plone/public
